nest init
andr37yen/Internship pull request #1
Opened 2023-06-07 07:59 UTC by andr37yen

@YuriiVasylyshyn, для ініціалізації проекту використав nest cli, після чого видалив непотрібні файли. Пізніше - також налаштував свагер, корси, змінив ts.config та eslintrc.js на запропоновані, а також добавив ConfigModule.

2023-06-07 09:39 UTC, YuriiVasylyshyn reviewed
1. Не забудь налаштувати CORS (фронта для цього в нас немає але для загального розуміння потрібно зробити)
2. `.env` потірбно додати в `gitignore`  аби не пощирювати важливі ключі і тд. Для прикладу сетапу конфігів на гіт можеш запушити файл `.env.example`
3. в кореневому каталозі створи папку `config` де парситимуться змінні середовища з `.env` файлу, для валідації використай [Joi](https://dev.to/rrgt19/ways-to-validate-environment-configuration-in-a-forfeature-config-in-nestjs-2ehp).  
4. винеси файли `app` модулю в окрему папку `src/modules/app/` і створи якийсь тестовий ендпоінт який повертає стрічку `ok` по типу GET `api/health`

2023-06-07 09:39 UTC, YuriiVasylyshyn commented on src/main.ts
> +    .setVersion('0.1')
версію можна дістати з `../package.json` і вже тут сетати

2023-06-07 12:05 UTC, andr37yen commented on src/main.ts
> +    .setVersion('0.1')
@YuriiVasylyshyn виправив у нових комітах

2023-06-07 12:15 UTC, andr37yen commented on src/main.ts
> +    .setVersion('0.1')
Але я щехотів би запитати на рахунок портів: в мене виходить дублікація запасних варіантів у файлі main.ts і configuration.ts, чи можна цього якось оптимально уникнути?

2023-06-07 12:28 UTC, YuriiVasylyshyn reviewed
1. папку `app` перенеси в папку `src/modules`
2. все ж таки краще папку `config` перенести в папку `src`
3. скрипт на запуск бази та міграції

2023-06-07 12:28 UTC, YuriiVasylyshyn commented on config/validation.ts
> +    PORT: Joi.number().required(),
```suggestion
    PORT: Joi.number().default(8080),
```

аби уникнути додаткових перевірок

2023-06-07 12:29 UTC, YuriiVasylyshyn commented on src/main.ts
> +    .setVersion('0.1')
@andr37yen відповів у ревʼю

2023-06-09 09:43 UTC, YuriiVasylyshyn reviewed
взагальному структуруй модулі так, це доволі зручно 

<img width="221" alt="Знімок екрана 2023-06-09 о 12 42 52" src="https://github.com/andr37yen/Internship/assets/44480026/5fd718f1-e82d-44a1-ad7b-6057e54f5f6e">

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on .example.env
> +POSTGRES_PASSWORD=postgres
```suggestion
# Server config
PORT=

# Database config
POSTGRES_PORT=
POSTGRES_HOST=
POSTGRES_DB=
POSTGRES_USER=
POSTGRES_PASSWORD=
```

ти ж розумієш, що це не допустимо.

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on .gitignore
> +ormconfig.ts
orm config не повинен бути в гіт ігнорі

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on ormconfig.example.ts
це можна видалити, оскільки цей конфіг не буде ігноруватись (якщо використовуватимеш змінні середовища то це буде безпечно для публікації на репозиторій)

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on src/config/interface.ts
> +  postgres_host?: string;
```suggestion
  postgres_user: string;
  postgres_password: string;
  postgres_db: string;
  postgres_port: number;
  postgres_host: string;
```

можливо так буде краще?

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on src/main.ts
> +  const configService = app.get(ConfigService);
```suggestion
  const configService = app.get<ConfigService<IAppConfig, true>>(ConfigService);
```
аби не доводилось строго типізувати змінні як описано нижче

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on src/main.ts
> +  });
можна один раз винести порт в змінну і використовувати її + якщо протипізувати конфіг то в загальному це виглядатиме так

`const port = configService.get('port', { infer: true })`

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on src/migrations/1686298131086-UserAdded.ts
правила форматування також повинні діяти на файли міграцій

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on src/modules/app/app.controller.spec.ts
> +import { AppService } from './app.service';
```suggestion
import { Test } from '@nestjs/testing';
import { AppController } from './app.controller';
import { AppService } from './app.service';

import type { TestingModule } from '@nestjs/testing';
```

старайся всюди переносити імпорти типів нижче

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on src/modules/carts/entities/cart.entity.ts
> +import { User } from 'src/modules/users/entities/user.entity';
```suggestion
import { User } from '../../../users/entities/user.entity';
```

не використовуй `src`

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on src/modules/carts/entities/cart.entity.ts
> +  }
навіщо тобі конструктор в сутностях?

2023-06-09 09:43 UTC, YuriiVasylyshyn commented on src/modules/categories/entities/category.entity.ts
> +  }
те саме питання для усіх

2023-06-09 12:23 UTC, YuriiVasylyshyn requested changes

2023-06-09 12:23 UTC, YuriiVasylyshyn commented on .gitignore
> +ormconfig.ts
!

2023-06-09 12:23 UTC, YuriiVasylyshyn commented on ormconfig.example.ts
цей файл не потрібен

2023-06-09 12:23 UTC, YuriiVasylyshyn commented on src/main.ts
> +    Logger.log('listening on port ' + configService.get('port'));
```suggestion
  const port = configService.get('port', { infer: true });
  
  await app.listen(port, () => {
    Logger.log('listening on port ' + port);
```

2023-06-14 12:22 UTC, YuriiVasylyshyn approved these changes

2023-06-14 12:29 UTC, merged